import { createRequestHandler } from 'react-router';
// @ts-ignore virtual module generated by @react-router/dev
import * as build from 'virtual:react-router/server-build';
import { getRawMarkdown } from 'virtual:mdx-docs/raw';
import { stripBase } from '~/lib/base';
import { firstPageSlug } from '~/lib/docs';
import { negotiateMarkdown } from '~/lib/negotiation';

declare module 'react-router' {
	interface AppLoadContext {
		cloudflare: {
			env: Env;
			ctx: ExecutionContext;
		};
	}
}

const handleRequest = createRequestHandler(build, import.meta.env.MODE);

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url);
		const appPath = stripBase(url.pathname);
		const negotiated = negotiateMarkdown(
			request,
			getRawMarkdown,
			firstPageSlug(),
			appPath,
		);
		if (negotiated) return negotiated;
		return handleRequest(request, { cloudflare: { env, ctx } });
	},
};
